<!-- contenet_main.tpl-->
		<div class="row">
		  <div class="col-sm-6 col-md-4">
			<div class="thumbnail">
			  <img src="/dev2.4/img/triangle-1.png" width="300" height="300" alt="Patches">
			  <div class="caption">
				<h3>Patches</h3>
				<p>A synthesizer patch (some manufacturers chose the term program) is a sound setting. Modular synthesizers used cables ("patch cords") to connect the different sound modules together. Since these machines had no memory to save settings, musicians wrote down the locations of the patch cables and knob positions on a "patch sheet" (which usually showed a diagram of the synthesizer). Ever since, an overall sound setting for any type of synthesizer has been referred to as a patch.</p>
				<p><a href="#" class="btn btn-primary" role="button">Create</a> <a href="#" class="btn btn-default" role="button">Search</a></p>
			  </div>
			</div>
		  </div>
		  <div class="col-sm-6 col-md-4">
			<div class="thumbnail">
			  <img src="/dev2.4/img/distort.png" width="300" height="300" alt="Direction">
			  <div class="caption">
				<h3>Direction</h3>
				<p>A full score is a large book showing the music of all instruments and/or voices in a composition lined up in a fixed order. It is large enough for a conductor to be able to read while directing orchestra or opera rehearsals and performances. In addition to their practical use for conductors leading ensembles, full scores are also used by musicologists, music theorists, composers and music students who are studying a given work.</p>
				<p><a href="#" class="btn btn-primary" role="button">See</a></p>
			  </div>
			</div>
		  </div>
		  <div class="col-sm-6 col-md-4">
			<div class="thumbnail">
			  <img src="/dev2.4/img/cube-1.png" width="300" height="300" alt="Classes">
			  <div class="caption">
				<h3>Classes</h3>
				<p>In object-oriented programming, a class is an extensible program-code-template for creating objects, providing initial values for state (member variables) and implementations of behavior (member functions or methods). In many languages, the class name is used as the name for the class (the template itself), the name for the default constructor of the class (a subroutine that creates objects), and as the type of objects generated by instantiating the class; these distinct concepts are easily conflated.</p>
				<p><a href="#" class="btn btn-primary" role="button">Create</a> <a href="#" class="btn btn-default" role="button">Search</a></p>
			  </div>
			</div>
		  </div>
		  <div class="col-sm-6 col-md-4">
			<div class="thumbnail">
			  <img src="/dev2.4/img/cube-2.png" width="300" height="300" alt="Objects">
			  <div class="caption">
				<h3>Objects</h3>
				<p>In computer science, an object can be a variable, a data structure, or a function or a method, and as such, is a location in memory having a value and possibly referenced by an identifier. In the class-based object-oriented programming paradigm, "object" refers to a particular instance of a class where the object can be a combination of variables, functions, and data structures.</p>
				<p><a href="#" class="btn btn-primary" role="button">Create</a> <a href="#" class="btn btn-default" role="button">Search</a></p>
			  </div>
			</div>
		  </div>
		</div>